### ISSUE TITLE
Dynamic Conditions not working with Elementor 3.21

### ISSUE THREAD

**Issue by jeffreysfridge** [RTO-Websites/dynamic-conditions#74] opened 2024-04-26 12:17 UTC
As noted by @dooza here: https://wordpress.org/support/topic/dynamic-conditions-not-working-on-elementor-3-21-0/

Since updating to Elementor 3.21.0 all of my widgets with Dynamic Conditions have stopped working. When I debug I get a blank value for all dynamic conditions. Once rolled back to 3.20.4 it works again.

**Comment by crazypsycho** [comment] 2024-04-26 12:39
We are looking at it, but actually cannot reproduce this issue.

**Comment by steveindzine** [comment] 2024-04-26 13:38
@crazypsycho would access to my staging site help?

**Comment by Dooza** [comment] 2024-04-26 14:14
@crazypsycho what would help you get to the bottom of this?

**Comment by crazypsycho** [comment] 2024-04-26 14:28
A screenshot of the widget-dynamiccondition-settings would be nice, and a screen of the debug-output when Debug-Mode is enabled.

**Comment by Dooza** [comment] 2024-04-26 14:34
![Screenshot 2024-04-26 153247](https://github.com/RTO-Websites/dynamic-conditions/assets/9673250/09a42d94-fedf-4127-a03d-3b9c4b4df092)
![Screenshot 2024-04-26 153236](https://github.com/RTO-Websites/dynamic-conditions/assets/9673250/68070f62-6ed0-4de2-b100-5546ce2654a9)
![Screenshot 2024-04-26 153200](https://github.com/RTO-Websites/dynamic-conditions/assets/9673250/e9bccf43-1f80-41e3-beef-6423784eb606)

**Comment by Dooza** [comment] 2024-04-26 14:37
This is it working with the previous version of Elementor:
![image](https://github.com/RTO-Websites/dynamic-conditions/assets/9673250/a17dbcf6-a2bd-4290-913f-8bdb0984112a)
and
![image](https://github.com/RTO-Websites/dynamic-conditions/assets/9673250/5975586c-5dd2-4316-8566-245d36fb5eb2)

**Comment by Webtica** [comment] 2024-04-30 18:34
Having the same issue with all conditions. Can provide extra info if needed.

**Comment by crazypsycho** [comment] 2024-05-06 06:31
Maybe it is some kind of conflict with an other plugin. Can you list your installed plugins and theme?

**Comment by jeffreysfridge** [comment] 2024-05-06 20:16
In my case, we're using a child theme of Hello Elementor and the following plugins:

ACF Content Analysis for Yoast SEO 
Advanced Custom Fields PRO 
Ajax Load More 
Ajax Load More: Pro 
All In One WP Security 
Breadcrumb NavXT 
Classic Editor 
Disable Comments 
Disable Version Caching 
DynamicConditions 
Elementor
Elementor Pro
Enable Media Replace
FlyingPress
Imagify
Link Whisper
MWW Scheduled Post Trigger
PublishPress Authors Pro
Safe SVG
Simple Custom Post Order
Simple History
Unlist Posts & Pages
WP External Links ConfigureGet PRO
WP SEO Structured Data Schema Pro
WP Sitemap Page
WP-SCSS
Yoast SEO
Yoast SEO Premium

**Comment by Dooza** [comment] 2024-05-07 07:42
Ok, we are using an Astra child theme, along with:

Advanced Custom Fields: Font Awesome | Version 4.0.6 by Matt Keys
Advanced Custom Fields PRO | Version 6.2.9 by WP Engine
Astra Pro | Version 4.6.8 by Brainstorm Force
Auto Image Attributes From Filename With Bulk Updater | Version 4.4 by Arun Basil Lal
Better Search Replace | Version 1.4.6 by WP Engine
Breeze | Version 2.1.7 by Cloudways
Change Mail Sender | Version 1.3.0 by WP Mail SMTP
Custom Adobe Fonts (Typekit) | Version 1.0.18 by Brainstorm Force
Custom Fonts | Version 2.1.5 by Brainstorm Force
Default featured image | Version 1.7.3 by Jan Willem Oostendorp
Delete Expired Transients | Version 2.0.7 by WebAware
Disable Gutenberg | Version 3.1.1 by Jeff Starr
DynamicConditions | Version 1.6.2 by RTO GmbH
Elementor | Version 3.20.4 by Elementor.com (Latest version: 3.21.4)
Elementor Pro | Version 3.20.3 by Elementor.com (Latest version: 3.21.2)
ElementsKit Lite | Version 3.1.2 by Wpmet (Latest version: 3.1.3)
Emage Hover Effects for Elementor | Version 4.5.2 by Blocksera
Enable Media Replace | Version 4.1.5 by ShortPixel
FacetWP | Version 4.2.12 by FacetWP, LLC
FacetWP - Conditional Logic | Version 1.4.2 by FacetWP, LLC
FacetWP - Elementor | Version 1.9 by FacetWP, LLC
FacetWP - Flyout menu | Version 0.8.2 by FacetWP, LLC
Max Mega Menu | Version 3.3.1 by megamenu.com
Max Mega Menu - Pro Addon | Version 2.4 by megamenu.com
Newbury Racecourse Elementor | Version 1.0.0 by InDzine
Object Cache Pro | Version 1.20.2 by Rhubarb Group
Permalink Manager Lite | Version 2.4.3.2 by Maciej Bis
Post Types Order | Version 2.2.1 by Nsp Code
Post Type Switcher | Version 3.3.1 by Triple J Software, Inc.
Qi Addons For Elementor | Version 1.6.9 by Qode Interactive (Latest version: 1.7.1)
Query Monitor | Version 3.16.2 by John Blackbourn
Regenerate Thumbnails | Version 3.1.6 by Alex Mills (Viper007Bond)
Solid Security Pro | Version 8.4.2 by SolidWP
The Plus Addons for Elementor | Version 5.4.2 by POSIMYTH (Latest version: 5.5.2)
The Plus Addons for Elementor - Pro | Version 5.4.1 by POSIMYTH (Latest version: 5.5.2)
Transients Manager | Version 2.0.5 by WPBeginner
Ultimate Addons for Elementor | Version 1.36.31 by Brainstorm Force
WP All Import - ACF Add-On | Version 3.3.8 by Soflyy
WP All Import Pro | Version 4.8.7 by Soflyy
WS Form PRO | Version 1.9.207 by WS Form
WS Form PRO - Dotdigital | Version 1.0.6 by WS Form
YIKES Simple Taxonomy Ordering | Version 2.3.4 by YIKES, Inc.
Yoast Duplicate Post | Version 4.5 by Enrico Battocchi & Team Yoast
Yoast SEO | Version 22.6 by Team Yoast

Newbury Racecourse Elementor is a custom plugin that I created that adds conditions, controls, dynamic tags, form actions and widgets.

This is a staging site I am working on, but have seen the issue on all of my sites that use Dynamic Conditions. I think I need to create a test site as well and see if I can reproduce the issue.

**Comment by Dooza** [comment] 2024-05-09 10:24
I have cloned my site, changed the theme to Hello Elementor, and reduced the plugins to a bare minimum:

Advanced Custom Fields PRO | Version 6.2.9 by WP Engine
DynamicConditions | Version 1.6.2 by RTO GmbH 
Elementor | Version 3.21.5 by Elementor.com
Elementor Pro | Version 3.21.2 by Elementor.com
Object Cache Pro | Version 1.21.0 by Rhubarb Group
Query Monitor | Version 3.16.2 by John Blackbourn

It tested my site and is still wasn't working.

So next up is Elementor Features. I took a look and the first thing I disabled was Optimized Control Loading. With this disabled Dynamic Conditions work! So what does Optimized Control Loading do? 

Steve

**Comment by Ericmuc** [comment] 2024-05-09 15:58
Thanks for this thread! This helped my to solve the same error in my system!
Is there a possibilty to have your plugin working with the optimized control loading active in the future?
(thanks for the great plugin, which helps me much!)

**Comment by saulposel** [comment] 2024-05-29 09:18
Hi. Thanks for the thread.

Just wandering if there was any update on the "optimized control loading" conflict / issue?

Thanks!

**Comment by crazypsycho** [comment] 2024-06-06 11:18
In new version 1.6.3 this issue is now fixed.

**Closed by crazypsycho** 2024-06-06 11:18 UTC

**Comment by steveindzine** [comment] 2024-06-06 11:21
Thank you @crazypsycho I will update and do some testing.
